import Foundation

enum DictionaryFixtures {
    static let ephemeral = "ephemeral | ɪˈfɛm(ə)r(ə)l, ɛˈfɛm(ə)r(ə)l | adjective lasting for a very short time: fashions are ephemeral: new ones regularly drive out the old | works of more than ephemeral interest. • (chiefly of plants) having a very short life cycle: chickweed is an ephemeral weed, producing several generations in one season. noun an ephemeral plant: ephemerals avoid the periods of drought as seeds. DERIVATIVES ephemerality | ɪfɛm(ə)ˈralɪti, ɪfiːm(ə)ˈralɪti | noun ephemerally adverb ephemeralness noun ORIGIN late 16th century: from Greek ephēmeros (see ephemera) + -al."

    static let dog = "dog | dɒɡ | noun 1 a domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, non-retractable claws, and a barking, howling, or whining voice. • a wild animal of the dog family. 2 derogatory an unpleasant, contemptible, or wicked man: he was interrupted by cries of 'dirty dog!'. • [with adjective] informal used to refer to a person of a specified kind in a tone of playful reprimand: your historian is a dull dog. verb (dogs, dogging, dogged) [with object] 1 follow (someone) closely and persistently: photographers seemed to dog her every step. PHRASES dog eat dog used to refer to a situation of fierce competition. PHRASAL VERBS dog out (dog someone out, dog out someone) US English informal criticize, insult, or treat someone harshly. ORIGIN Old English docga, of unknown origin."

    static let cat = "cat 1 | kat | noun 1 a small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed. Felis catus, family Felidae (the cat family); it was probably domesticated in ancient Egypt from the local race of wildcat. The cat family also includes the ocelot, serval, margay, lynx, and the big cats • a wild animal of the cat family. See also big cat: a marbled cat. • used in names of catlike animals of other families, e.g. native cat, ring-tailed cat. • derogatory a malicious or spiteful woman: his mother called me an old cat. 2 informal, mainly North American English (especially among jazz enthusiasts) a man: this West Coast cat had managed him since the early 80s | the cat went crazy on the horn. 3 historical a short tapered stick used in the game of tipcat. verb (cats, catting, catted) [with object] Nautical raise (an anchor) from the surface of the water to the cathead: I kept her off the wind and sailing free until I had the anchor catted. PHRASES let the cat out of the bag informal reveal a secret carelessly or by mistake: now that Viola had let the cat out of the bag, she had no option but to confess. ORIGIN Old English catt, catte, of Germanic origin; related to Dutch kat and German Katze; reinforced in Middle English by forms from late Latin cattus."
}
